OtsuSplit WIP
light-curve/light-curve-feature pull request #58
Opened 2022-06-29 13:28 UTC by anlava

2022-07-03 08:33 UTC, hombit requested changes

2022-07-03 08:33 UTC, hombit commented on src/features/otsu_split.rs
> +Matwey Kornilov Otsu thresholding algorithm realization was used as a reference:
Matwey Kornilov's

2022-07-03 08:33 UTC, hombit commented on src/features/otsu_split.rs
> +        }
We can do it using `msorted.minimum()` and `msorted.maximum()`, it should be faster in the case when `m` is not pre-sorted

2022-07-03 08:33 UTC, hombit commented on src/features/otsu_split.rs
> +        for &m in msorted.iter() {
We can use `.enumerate()` or `(1..).zip(msorted.iter())` instead, in this case we don't need a mutable `w`

2022-07-03 08:33 UTC, hombit commented on src/features/otsu_split.rs
> +        let mean_upper;
I believe we can try to find these values iteratively in the for-loop. `mean_upper - mean_lower` is just `dm`, `std_lower` should be faster to find in the for-loop, and `std_upper` is probably a function of `std_lower`, `dm` and `get_nonzero_m_std2(ts)?`.

2022-07-03 08:33 UTC, hombit commented on src/features/otsu_split.rs
> +            if w == count {
It looks like it is possible only if time series is flat, but I could be wrong

2022-07-03 08:33 UTC, hombit commented on src/features/otsu_split.rs
> +#[cfg(test)]
Please test more edge-cases: 1) minimum number of observations, 2) `w == count` (if you could find such an example for non-flat time-series), 3) w == 2

2022-07-03 08:35 UTC, hombit commented on src/features/otsu_split.rs
> +        let mut dm = T::zero();
Maybe rename to `delta_mean`?

2022-09-05 14:16 UTC, hombit commented
1. Docs: say about possible multiple maxima
2. Add benchmark here: https://github.com/light-curve/light-curve-feature/blob/e8b54b0a60b0259b2382093d5ab56f923287ab0d/benches/extractor.rs#L17
`cargo bench -- FeatureExtractor`

2022-09-06 20:45 UTC, anlava commented
Benchmark results:

**FeatureExtractor otsu_mean_diff: [100; f64]                                                                            
                        time:   [264.12 ns 264.32 ns 264.55 ns]**
Found 10 outliers among 100 measurements (10.00%)
  3 (3.00%) low mild
  3 (3.00%) high mild
  4 (4.00%) high severe

**FeatureExtractor otsu_mean_diff: [1000; f64]                                                                             
                        time:   [1.8969 us 1.8988 us 1.9010 us]**
Found 12 outliers among 100 measurements (12.00%)
  3 (3.00%) high mild
  9 (9.00%) high severe

2022-09-06 21:22 UTC, hombit approved these changes

2022-09-06 21:24 UTC, merged